## Preprocessing module :

#### Import libraries :

In [1]:
import pandas as pd

#### Load data :

In [2]:
raw_csv_data = pd.read_csv('Absenteeism_data.csv')
raw_csv_data.head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

#### Make a copy dataframe :

In [3]:
df = raw_csv_data.copy()
df.head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

 #### Summary :

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
ID                           700 non-null int64
Reason for Absence           700 non-null int64
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.7+ KB

#### Drop columns :

In [5]:
df = df.drop(['ID'], axis=1)
df_no_age = df.drop(['Age'], axis=1)

#### Analysing variables/features :

In [6]:
df['Reason for Absence'].min()

0

In [7]:
df['Reason for Absence'].max()

28

In [8]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [9]:
len(df['Reason for Absence'].unique())

28

In [10]:
#Find missing value :
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

#### Dummies for categorical nominals :

In [11]:
reason_columns = pd.get_dummies(df['Reason for Absence'])
reason_columns

,0,1,2,3,4,5,6,7,8,9,...,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
10,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
28,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
671,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
672,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
673,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
674,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
675,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
676,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
677,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
678,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
679,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
680,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
681,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
682,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
683,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
684,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
686,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
688,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
689,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
690,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
691,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
692,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
693,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
694,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [12]:
reason_columns['check'] = reason_columns.sum(axis=1)
reason_columns

,0,1,2,3,4,5,6,7,8,9,...,19,21,22,23,24,25,26,27,28,check
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
6,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
8,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
9,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
10,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
17,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
671,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
672,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
673,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
674,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
675,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
676,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
677,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
678,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
679,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
680,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
681,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
682,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
683,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
684,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
686,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
688,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
689,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
690,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
691,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
692,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
693,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
694,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
696,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [13]:
reason_columns = reason_columns.drop(['check'], axis =1)

In [14]:
#Splitting Age column :
age_columns = pd.get_dummies(df['Age'])
age_columns.head()

,27,28,29,30,31,32,33,34,36,37,...,39,40,41,43,46,47,48,49,50,58
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
age_columns['age_dummies'] = age_columns.sum(axis=1)
age_columns.head()
df_no_age = age_columns.copy()
df_no_age.head()

,27,28,29,30,31,32,33,34,36,37,...,40,41,43,46,47,48,49,50,58,age_dummies
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [16]:
age_columns = age_columns.drop(['age_dummies'], axis=1)

In [17]:
reason_columns = pd.get_dummies(df['Reason for Absence'],drop_first=True)
reason_columns.head()

,1,2,3,4,5,6,7,8,9,10,...,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

#### Group features :

In [18]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [19]:
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64)

In [20]:
df = df.drop(['Reason for Absence'],axis=1)
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [21]:
reason_columns.loc[:,1:14]

     1   2   3   4   5   6   7   8   9   10  11  12  13  14
0     0   0   0   0   0   0   0   0   0   0   0   0   0   0
1     0   0   0   0   0   0   0   0   0   0   0   0   0   0
2     0   0   0   0   0   0   0   0   0   0   0   0   0   0
3     0   0   0   0   0   0   1   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   0   0   0   0   0   0   0
5     0   0   0   0   0   0   0   0   0   0   0   0   0   0
6     0   0   0   0   0   0   0   0   0   0   0   0   0   0
7     0   0   0   0   0   0   0   0   0   0   0   0   0   0
8     0   0   0   0   0   0   0   0   0   0   0   0   0   0
9     0   0   0   0   0   0   0   0   0   0   0   0   0   0
10    1   0   0   0   0   0   0   0   0   0   0   0   0   0
11    1   0   0   0   0   0   0   0   0   0   0   0   0   0
12    0   0   0   0   0   0   0   0   0   0   1   0   0   0
13    0   0   0   0   0   0   0   0   0   0   1   0   0   0
14    0   0   0   0   0   0   0   0   0   0   0   0   0   0
15    0   0   0   0   0   0   0   0   0   0   0   0   0   1
16    0   0   0   0   0   0   0   0   0   0   0   0   0   0
17    0   0   0   0   0   0   0   0   0   0   0   0   0   0
18    0   0   0   0   0   0   0   0   0   0   1   0   0   0
19    0   0   0   0   0   0   0   0   0   0   0   0   0   0
20    0   0   0   0   0   0   0   0   0   1   0   0   0   0
21    0   0   0   0   0   0   0   0   0   0   1   0   0   0
22    0   0   0   0   0   0   0   0   0   0   0   0   1   0
23    0   0   0   0   0   0   0   0   0   0   0   0   0   0
24    0   0   0   0   0   0   0   0   0   0   0   0   0   0
25    0   0   0   0   0   0   0   0   0   0   0   0   0   0
26    0   0   0   0   0   0   0   0   0   0   0   0   0   0
27    0   0   0   0   0   0   0   0   0   0   0   0   0   0
28    0   0   0   0   0   0   0   0   0   0   0   0   0   0
29    0   0   0   0   0   0   0   0   0   0   0   0   0   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
670   0   0   0   0   0   0   0   0   0   0   0   0   0   0
671   0   0   0   0   0   0   0   0   0   0   0   0   0   0
672   0   0   0   0   0   0   0   0   0   0   0   0   0   1
673   0   0   0   0   0   0   0   0   0   0   0   0   0   0
674   0   0   0   0   0   0   0   0   0   0   0   0   0   0
675   0   0   0   0   0   0   0   0   0   0   0   0   0   0
676   0   0   0   0   0   0   0   0   0   0   0   0   0   0
677   0   0   0   0   0   0   0   1   0   0   0   0   0   0
678   0   0   0   0   0   0   0   0   0   0   0   0   0   0
679   0   0   0   0   0   0   0   0   0   0   0   0   1   0
680   0   0   0   0   0   0   0   0   0   0   0   0   0   0
681   0   0   0   0   0   0   0   0   0   0   0   0   0   1
682   0   0   0   0   0   0   0   0   0   0   0   0   0   0
683   0   0   0   0   0   0   0   0   0   0   0   0   0   0
684   0   0   0   0   0   0   0   0   0   0   0   0   0   0
685   0   0   0   0   0   0   0   0   0   0   0   0   0   0
686   0   0   0   0   1   0   0   0   0   0   0   0   0   0
687   0   0   0   0   0   0   0   0   0   0   0   0   0   0
688   0   0   0   0   0   0   0   0   0   0   0   0   0   0
689   0   0   0   0   0   0   0   0   0   0   0   0   0   0
690   0   0   0   0   0   0   0   0   0   0   0   0   0   0
691   0   0   0   0   0   0   0   0   0   0   0   0   0   0
692   0   0   0   0   0   0   0   0   0   1   0   0   0   0
693   0   0   0   0   0   0   0   0   0   1   0   0   0   0
694   0   0   0   0   0   0   0   0   0   0   0   0   0   0
695   0   0   0   0   0   0   0   0   0   1   0   0   0   0
696   0   0   0   0   0   1   0   0   0   0   0   0   0   0
697   0   0   0   0   0   0   0   0   0   1   0   0   0   0
698   0   0   0   0   0   0   0   0   0   0   0   0   0   0
699   0   0   0   0   0   0   0   0   0   0   0   0   0   0

[700 rows x 14 columns]

In [22]:
reason_type_1 = reason_columns.loc[:,1:14].max(axis =1)
reason_type_2 = reason_columns.loc[:,15:17].max(axis =1)
reason_type_3 = reason_columns.loc[:,18:21].max(axis =1)
reason_type_4 = reason_columns.loc[:,22:].max(axis =1)

#### Concatinate groups :

In [23]:
df = pd.concat([df,reason_type_1,reason_type_2, reason_type_3,reason_type_4],axis=1)
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

#### Reassign column names :

In [24]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [25]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [26]:
df.columns = column_names
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Reason_1,Reason_2,Reason_3,Reason_4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

In [27]:
df_no_age.columns.values

array([27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 43, 46, 47,
       48, 49, 50, 58, 'age_dummies'], dtype=object)

In [28]:
df_concatenated = pd.concat([df_no_age,age_dummies],axis=1)

NameError: name 'age_dummies' is not defined

#### Reorder Columns :

In [29]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [30]:
df = df[column_names_reordered]
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2